name: Azure Back-End PipeLine

variables:
  - name: working-dir
    value: './back-end'

pr: none
trigger:
  #batch: true
  branches:
    include:
    - development 
  paths:
    include: 
      - $(working-dir)/*

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    CI=false
    npm install
  displayName: 'npm install and build'
  workingDirectory: $(working-dir)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(working-dir)/test
    ArtifactName: 'drop'
    publishLocation: 'Container'
